lib/ip_lab_web/router.ex
defmodule IpLabWeb.Router do
  use IpLabWeb, :router

  import IpLabWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {IpLabWeb.LayoutView, :root}
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IpLabWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/", EquipmentLive.Index, :index

    live "/categories", CategoryLive.Index, :index
    live "/categories/new", CategoryLive.New, :new
    live "/categories/:id/edit", CategoryLive.Edit, :edit

    live "/equipment", EquipmentLive.Index, :index
    live "/equipment/new", EquipmentLive.New, :new
    live "/equipment/:id/edit", EquipmentLive.Edit, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", IpLabWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:browser, :require_authenticated_user]
      live_dashboard "/dashboard", metrics: IpLabWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", IpLabWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", IpLabWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", IpLabWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/ip_lab_web/views/layout_view.ex
defmodule IpLabWeb.LayoutView do
  use IpLabWeb, :view
end

lib/ip_lab_web/templates/layout/_edit.html.eex
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708l-3-3zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207l6.5-6.5zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.499.499 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11l.178-.178z"/>
</svg>

lib/ip_lab_web/templates/layout/_remove.html.eex
<svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash-fill" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
</svg>

lib/ip_lab_web/templates/layout/_user_menu.html.eex
<ul class="navbar-nav ml-auto">
  <li class="nav-item">
    <%= if @current_user do %>
      <%= link to: Routes.user_settings_path(@conn, :edit) do %>
        <img src="/images/dummy-avatar.jpg" class="rounded-circle avatar-nav mr-auto">
      <% end %>
    <% else %>
      <%= link "Вход", to: Routes.user_session_path(@conn, :new), class: "nav-link" %>
    <% end %>
  </li>
</ul>

lib/ip_lab_web/templates/layout/app.html.eex
<p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
<p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
<%= @inner_content %>

lib/ip_lab_web/templates/layout/root.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>IpLab · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
    <script defer type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </head>
  <body>
    <header>
      <section class="container">
        <div class="fixed-top">
          <div class="collapse" id="navbarToggleExternalContent">
            <div class="bg-dark p-4">
              <h5 class="text-white h4">Система учета вычислительной техники</h5>
              <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                  <a class="nav-link" href="/equipment">Оборудование</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="/categories">Категории</a>
                </li>
                <%= if @current_user do %>
                  <li class="nav-item">
                    <%= link "Выход", to: Routes.user_session_path(@conn, :delete), method: :delete, class: "nav-link" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
          <nav class="navbar navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <%= render "_user_menu.html", assigns %>
          </nav>
        </div>
      </section>
    </header>
    <main role="main" class="pt-5 m-5">
      <%= @inner_content %>
    </main>
    <footer class="footer">
      <div class="container text-center">
          <span class="text-muted">Станислав Будаев &copy; 2020</span>
      </div>
    </footer>
  </body>
</html>