lib/ip_lab_web/router.ex
defmodule IpLabWeb.Router do
  use IpLabWeb, :router

  import IpLabWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_root_layout, {IpLabWeb.LayoutView, :root}
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", IpLabWeb do
    pipe_through [:browser, :require_authenticated_user]

    live "/", EquipmentLive.Index, :index

    live "/categories", CategoryLive.Index, :index
    live "/categories/new", CategoryLive.New, :new
    live "/categories/:id/edit", CategoryLive.Edit, :edit

    live "/equipment", EquipmentLive.Index, :index
    live "/equipment/new", EquipmentLive.New, :new
    live "/equipment/:id/edit", EquipmentLive.Edit, :edit
  end

  # Other scopes may use custom stacks.
  # scope "/api", IpLabWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through [:browser, :require_authenticated_user]
      live_dashboard "/dashboard", metrics: IpLabWeb.Telemetry
    end
  end

  ## Authentication routes

  scope "/", IpLabWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", IpLabWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings/update_password", UserSettingsController, :update_password
    put "/users/settings/update_email", UserSettingsController, :update_email
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", IpLabWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :confirm
  end
end

lib/ip_lab_web/controllers/user_registration_controller.ex
defmodule IpLabWeb.UserRegistrationController do
  use IpLabWeb, :controller

  alias IpLab.Accounts
  alias IpLab.Accounts.User
  alias IpLabWeb.UserAuth

  def new(conn, _params) do
    changeset = Accounts.change_user_registration(%User{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.register_user(user_params) do
      {:ok, user} ->
        {:ok, _} =
          Accounts.deliver_user_confirmation_instructions(
            user,
            &Routes.user_confirmation_url(conn, :confirm, &1)
          )

        conn
        |> put_flash(:info, "User created successfully.")
        |> UserAuth.log_in_user(user)

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end
end

lib/ip_lab_web/views/user_registration_view.ex
defmodule IpLabWeb.UserRegistrationView do
  use IpLabWeb, :view
end

lib/ip_lab_web/templates/user_registration/new.html.eex
<section>

  <h1>Регистрация</h1>

  <%= form_for @changeset, Routes.user_registration_path(@conn, :create), fn f -> %>
    <%= if @changeset.action do %>
      <div class="alert alert-danger">
        <p>Упс, что-то пошло не так! Проверьте ошибки указанные ниже.</p>
      </div>
    <% end %>

    <div class="form-group">
      <%= label f, :email %>
      <%= email_input f, :email, required: true, class: "form-control" %>
      <%= error_tag f, :email %>
    </div>

    <div class="form-group">
      <%= label f, :password, "Пароль" %>
      <%= password_input f, :password, required: true, class: "form-control" %>
      <%= error_tag f, :password %>
    </div>

    <div class="m-2">
      <%= submit "Зарегистрироваться", class: "btn btn-primary" %>
    </div>
  <% end %>

  <p class="m-2">
    <%= link "Вход", to: Routes.user_session_path(@conn, :new) %> |
    <%= link "Забыли пароль?", to: Routes.user_reset_password_path(@conn, :new) %>
  </p>
</section>